name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-api:
    name: Build & Push API Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-arch emulation
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push API image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/devops-api:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/devops-api:cache,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-api:${{ github.sha }}

  build-frontend:
    name: Build & Push Frontend Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('status-page/package.json', 'status-page/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm- }}

      - name: Set up QEMU for multi-arch emulation
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./status-page
          file: ./status-page/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/devops-status-page:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/devops-status-page:cache,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-status-page:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-status-page:${{ github.sha }}
