name: Build & Push API + Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Clona tu repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Configura QEMU para emulación multi-arquitectura
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3) Prepara Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4) Login a Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5) Build & Push de la API (Dockerfile en la raíz) - Multi-arquitectura
      - name: Build & Push API image
        uses: docker/build-push-action@v4
        with:
          context: .               
          file: ./Dockerfile       
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-api:${{ github.sha }}

      # 6) Build & Push del Frontend (Dockerfile en status-page/) - Multi-arquitectura
      - name: Build & Push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./status-page    
          file: ./status-page/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-status-page:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-status-page:${{ github.sha }}
