name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push ${{ matrix.target }} for ${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: api
            arch: linux/amd64
            arch_tag: amd64
          - target: api
            arch: linux/arm64
            arch_tag: arm64
          - target: frontend
            arch: linux/amd64
            arch_tag: amd64
          - target: frontend
            arch: linux/arm64
            arch_tag: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-arch emulation
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache npm dependencies (only for frontend)
        if: matrix.target == 'frontend'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('status-page/package.json', 'status-page/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.target == 'api' && '.' || './status-page' }}
          file: ${{ matrix.target == 'api' && './Dockerfile' || './status-page/Dockerfile' }}
          push: true
          platforms: ${{ matrix.arch }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/devops-${{ matrix.target }}:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/devops-${{ matrix.target }}:cache,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-${{ matrix.target }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-${{ matrix.target }}:${{ github.sha }}-${{ matrix.arch_tag }}

