name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
      DATABASE_URL: "sqlite:///:memory:"
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build API service image
        run: docker-compose build web

      - name: Run API tests in container
        run: docker-compose run --rm --no-deps -e DATABASE_URL="sqlite:///:memory:" web pytest app/tests/
